apiVersion: v1
kind: ConfigMap
metadata:
  name: logiflow-config
  namespace: logiflow
data:
  # Database URLs
  AUTH_DB_URL: "jdbc:postgresql://authdb-service:5432/authdb"
  PEDIDO_DB_URL: "jdbc:postgresql://pedidodb-service:5432/pedidodb"
  FLEET_DB_URL: "jdbc:postgresql://fleetdb-service:5432/fleetdb"
  BILLING_DB_URL: "jdbc:postgresql://billingdb-service:5432/billingdb"
  
  # Database Config
  DB_USERNAME: "logiuser"
  DB_DRIVER: "org.postgresql.Driver"
  DB_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  
  # RabbitMQ Config
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "logiflow"
  RABBITMQ_VHOST: "/"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8081"
  PEDIDO_SERVICE_URL: "http://pedido-service:8082"
  FLEET_SERVICE_URL: "http://fleet-service:8083"
  BILLING_SERVICE_URL: "http://billing-service:8084"
  
  # JPA Config
  JPA_HIBERNATE_DDL_AUTO: "update"
  JPA_SHOW_SQL: "false"
  JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_APP: "DEBUG"
