# IMPORTANTE: Este archivo contiene secretos en base64
# En producci√≥n, usar kubectl create secret o un gestor de secretos como Sealed Secrets / Vault
# 
# Para generar valores base64:
# echo -n "tu-valor" | base64

apiVersion: v1
kind: Secret
metadata:
  name: logiflow-secrets
  namespace: logiflow
type: Opaque
data:
  # PostgreSQL Password (logipass123)
  db-password: bG9naXBhc3MxMjM=
  
  # RabbitMQ Password (logiflow123)
  rabbitmq-password: bG9naWZsb3cxMjM=
  
  # JWT Secret (miSuperSecreto123@LogiFlow2024SecureKey)
  jwt-secret: bWlTdXBlclNlY3JldG8xMjNATG9naUZsb3cyMDI0U2VjdXJlS2V5
  
  # pgAdmin Password (admin123)
  pgadmin-password: YWRtaW4xMjM=
