server:
  port: 8085

spring:
  application:
    name: graphql-service
  
  graphql:
    graphiql:
      enabled: false  # Deshabilitado, usamos nuestra propia interfaz
    path: /graphql
    schema:
      printer:
        enabled: true
    websocket:
      path: /graphql-ws
  
  web:
    resources:
      static-locations: classpath:/static/
    
# URLs de otros microservicios
services:
  pedido:
    url: http://localhost:8082
  fleet:
    url: http://localhost:8083
  billing:
    url: http://localhost:8084

logging:
  level:
    graphql: DEBUG
    com.entregaexpress: DEBUG
